package com.vachel.sudo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vachel.sudo.dao.Examination;
import com.vachel.sudo.dao.Record;
import com.vachel.sudo.dao.ArchiveBean;

import com.vachel.sudo.dao.ExaminationDao;
import com.vachel.sudo.dao.RecordDao;
import com.vachel.sudo.dao.ArchiveBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig examinationDaoConfig;
    private final DaoConfig recordDaoConfig;
    private final DaoConfig archiveBeanDaoConfig;

    private final ExaminationDao examinationDao;
    private final RecordDao recordDao;
    private final ArchiveBeanDao archiveBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        examinationDaoConfig = daoConfigMap.get(ExaminationDao.class).clone();
        examinationDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        archiveBeanDaoConfig = daoConfigMap.get(ArchiveBeanDao.class).clone();
        archiveBeanDaoConfig.initIdentityScope(type);

        examinationDao = new ExaminationDao(examinationDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);
        archiveBeanDao = new ArchiveBeanDao(archiveBeanDaoConfig, this);

        registerDao(Examination.class, examinationDao);
        registerDao(Record.class, recordDao);
        registerDao(ArchiveBean.class, archiveBeanDao);
    }
    
    public void clear() {
        examinationDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
        archiveBeanDaoConfig.clearIdentityScope();
    }

    public ExaminationDao getExaminationDao() {
        return examinationDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public ArchiveBeanDao getArchiveBeanDao() {
        return archiveBeanDao;
    }

}
