package com.vachel.sudo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXAMINATION".
*/
public class ExaminationDao extends AbstractDao<Examination, String> {

    public static final String TABLENAME = "EXAMINATION";

    /**
     * Properties of entity Examination.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Key = new Property(0, String.class, "key", true, "KEY");
        public final static Property Exam = new Property(1, String.class, "exam", false, "EXAM");
        public final static Property Difficulty = new Property(2, int.class, "difficulty", false, "DIFFICULTY");
        public final static Property SortIndex = new Property(3, int.class, "sortIndex", false, "SORT_INDEX");
        public final static Property TipsCount = new Property(4, int.class, "tipsCount", false, "TIPS_COUNT");
        public final static Property TakeTime = new Property(5, long.class, "takeTime", false, "TAKE_TIME");
        public final static Property FinishDate = new Property(6, long.class, "finishDate", false, "FINISH_DATE");
        public final static Property Mode = new Property(7, int.class, "mode", false, "MODE");
        public final static Property Version = new Property(8, int.class, "version", false, "VERSION");
    }


    public ExaminationDao(DaoConfig config) {
        super(config);
    }
    
    public ExaminationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXAMINATION\" (" + //
                "\"KEY\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: key
                "\"EXAM\" TEXT NOT NULL ," + // 1: exam
                "\"DIFFICULTY\" INTEGER NOT NULL ," + // 2: difficulty
                "\"SORT_INDEX\" INTEGER NOT NULL ," + // 3: sortIndex
                "\"TIPS_COUNT\" INTEGER NOT NULL ," + // 4: tipsCount
                "\"TAKE_TIME\" INTEGER NOT NULL ," + // 5: takeTime
                "\"FINISH_DATE\" INTEGER NOT NULL ," + // 6: finishDate
                "\"MODE\" INTEGER NOT NULL ," + // 7: mode
                "\"VERSION\" INTEGER NOT NULL );"); // 8: version
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXAMINATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Examination entity) {
        stmt.clearBindings();
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
        stmt.bindString(2, entity.getExam());
        stmt.bindLong(3, entity.getDifficulty());
        stmt.bindLong(4, entity.getSortIndex());
        stmt.bindLong(5, entity.getTipsCount());
        stmt.bindLong(6, entity.getTakeTime());
        stmt.bindLong(7, entity.getFinishDate());
        stmt.bindLong(8, entity.getMode());
        stmt.bindLong(9, entity.getVersion());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Examination entity) {
        stmt.clearBindings();
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
        stmt.bindString(2, entity.getExam());
        stmt.bindLong(3, entity.getDifficulty());
        stmt.bindLong(4, entity.getSortIndex());
        stmt.bindLong(5, entity.getTipsCount());
        stmt.bindLong(6, entity.getTakeTime());
        stmt.bindLong(7, entity.getFinishDate());
        stmt.bindLong(8, entity.getMode());
        stmt.bindLong(9, entity.getVersion());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Examination readEntity(Cursor cursor, int offset) {
        Examination entity = new Examination( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // key
            cursor.getString(offset + 1), // exam
            cursor.getInt(offset + 2), // difficulty
            cursor.getInt(offset + 3), // sortIndex
            cursor.getInt(offset + 4), // tipsCount
            cursor.getLong(offset + 5), // takeTime
            cursor.getLong(offset + 6), // finishDate
            cursor.getInt(offset + 7), // mode
            cursor.getInt(offset + 8) // version
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Examination entity, int offset) {
        entity.setKey(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setExam(cursor.getString(offset + 1));
        entity.setDifficulty(cursor.getInt(offset + 2));
        entity.setSortIndex(cursor.getInt(offset + 3));
        entity.setTipsCount(cursor.getInt(offset + 4));
        entity.setTakeTime(cursor.getLong(offset + 5));
        entity.setFinishDate(cursor.getLong(offset + 6));
        entity.setMode(cursor.getInt(offset + 7));
        entity.setVersion(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Examination entity, long rowId) {
        return entity.getKey();
    }
    
    @Override
    public String getKey(Examination entity) {
        if(entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Examination entity) {
        return entity.getKey() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
